### ISSUE TITLE
changelog notes protected branch

### ISSUE THREAD

**Issue by mkatsanto** [zavolanlab/zarp#129]
**Describe the bug**
The CHANGELOG.md is not working properly in this workflow. The issue is that this action is adding the history of commits to the CHANGELOG.md and then pushes the commit to the protected-dev branch, which is not allowed. The only workarounds for this is to allow this action to act as an administrator or create some ssh key that allows it to force push to the protected dev branch. The question is, do we want that? The other alternative would be to add the commit to each of the PRs upon the pull request. This would not need to bypass any protections, but I am not sure how feasible it is https://github.com/requarks/changelog-action. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by uniqueg** [comment]
Hi @mkatsanto, I have created a bot account for the `zavolanlab` organization. Its name is `zavolab`. I have also given the bot account permissions to force push to the `dev` branch. I have further created a personal access token for the user with the `repo` and `workflow` scopes (as described [here](https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs)). I have then created an organization secret `AUTO_COMMIT` with the value of that token.

I _think_ if you follow the instructions in the [`git-auto-commit-action` docs](https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs), it will hopefully work. In particular, you need to do:

```yaml
- uses: actions/checkout@v3
  with:
    token: ${{ secrets.AUTO_COMMIT }}
```

> Note that you should probably increase the `actions/checkout` version to `v3`, it's currently at `v2`.

And:

```yaml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        ...
        push_options: --force
```
