### ISSUE TITLE
fix: segfault upon SRA download workflow reruns

### ISSUE THREAD

**Issue by uniqueg** [zavolanlab/zarp#132]
**Describe the bug**

At least under some conditions, rerunning the SRA download workflow leads to a segfault in `pigz`. I did not explore in detail when and when it does not occur (there is no additional information!), but presumably it has to do with the fact that the current implementation compresses the `FASTQ` files in place, rather than writing them to an output file (or two, in the case of paired-end samples). Another contributing factor may possibly be that in the context of _ZARP-cli_, the working directory is explicitly set and some inputs and the final output are residing in particular, run-specifc folders, but I did not explore this in detail.

**To Reproduce**

In principle, rerunning the following line should reproduce the error:

```bash
snakemake
    --snakefile /path/to/home/repos/zarp/workflow/rules/sra_download.smk \
    --cores 1 \
    --configfile /path/to/home/.zarp/runs/sra_download/runs/UUTF8A/config.yaml \
    --directory /path/to/home/.zarp/runs/sra_download
    --use-conda
```

with the contents of `config.yaml` being:

```yaml
cluster_log_dir: /path/to/home/.zarp/runs/sra_download/logs/cluster
log_dir: /path/to/home/.zarp/runs/sra_download/logs
outdir: /path/to/home/.zarp/runs/sra_download/sra
samples: /path/to/home/.zarp/runs/sra_download/runs/mYrUnId/samples_remote.tsv
samples_out: /path/to/home/.zarp/runs/sra_download/runs/mYrUnId/samples_remote_loc.tsv
```

and the sample table being:

```console
sample
SRR1525892
SRR9004891
SRR9004893
```

**Expected behavior**

Rerunning the same command should not cause an error and should not attempt to compress FASTQ files again.
